[project]
name = "ofd2img"
version = "0.1.1"
description = "OFD to Image/PDF transformation library"
authors = [
    { name = "Sun", email = "" }
]
dependencies = [
    "reportlab>=3.6.11",
    "xmltodict>=0.13.0",
    "loguru>=0.7.2",
    "fontTools>=4.43.1",
    "PyMuPDF>=1.23.4",
    "pyasn1>=0.6.0",
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["ofd2img"]

[tool.hatch.build]
exclude = [
  "test",
  "tests",
  "ofd2jpg.py",
]
